/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './iq-select2.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import8 from '@angular/http/src/backends/browser_xhr';
import * as import9 from '@angular/http/src/base_response_options';
import * as import10 from '@angular/http/src/backends/xhr_backend';
import * as import11 from '@angular/http/src/base_request_options';
import * as import12 from '@angular/forms/src/form_builder';
import * as import13 from '@angular/core/src/di/injector';
import * as import14 from '@angular/core/src/i18n/tokens';
import * as import15 from '@angular/http/src/interfaces';
import * as import16 from '@angular/http/src/http';
class IqSelect2ModuleInjector extends import0.NgModuleInjector<import1.IqSelect2Module> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _HttpModule_3:import5.HttpModule;
  _ReactiveFormsModule_4:import4.ReactiveFormsModule;
  _IqSelect2Module_5:import1.IqSelect2Module;
  __NgLocalization_6:import6.NgLocaleLocalization;
  __RadioControlRegistry_7:import7.RadioControlRegistry;
  __BrowserXhr_8:import8.BrowserXhr;
  __ResponseOptions_9:import9.BaseResponseOptions;
  __XSRFStrategy_10:any;
  __XHRBackend_11:import10.XHRBackend;
  __RequestOptions_12:import11.BaseRequestOptions;
  __Http_13:any;
  __FormBuilder_14:import12.FormBuilder;
  constructor(parent:import13.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_6():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import6.NgLocaleLocalization(this.parent.get(import14.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _RadioControlRegistry_7():import7.RadioControlRegistry {
    if ((this.__RadioControlRegistry_7 == null)) { (this.__RadioControlRegistry_7 = new import7.RadioControlRegistry()); }
    return this.__RadioControlRegistry_7;
  }
  get _BrowserXhr_8():import8.BrowserXhr {
    if ((this.__BrowserXhr_8 == null)) { (this.__BrowserXhr_8 = new import8.BrowserXhr()); }
    return this.__BrowserXhr_8;
  }
  get _ResponseOptions_9():import9.BaseResponseOptions {
    if ((this.__ResponseOptions_9 == null)) { (this.__ResponseOptions_9 = new import9.BaseResponseOptions()); }
    return this.__ResponseOptions_9;
  }
  get _XSRFStrategy_10():any {
    if ((this.__XSRFStrategy_10 == null)) { (this.__XSRFStrategy_10 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_10;
  }
  get _XHRBackend_11():import10.XHRBackend {
    if ((this.__XHRBackend_11 == null)) { (this.__XHRBackend_11 = new import10.XHRBackend(this._BrowserXhr_8,this._ResponseOptions_9,this._XSRFStrategy_10)); }
    return this.__XHRBackend_11;
  }
  get _RequestOptions_12():import11.BaseRequestOptions {
    if ((this.__RequestOptions_12 == null)) { (this.__RequestOptions_12 = new import11.BaseRequestOptions()); }
    return this.__RequestOptions_12;
  }
  get _Http_13():any {
    if ((this.__Http_13 == null)) { (this.__Http_13 = import5.httpFactory(this._XHRBackend_11,this._RequestOptions_12)); }
    return this.__Http_13;
  }
  get _FormBuilder_14():import12.FormBuilder {
    if ((this.__FormBuilder_14 == null)) { (this.__FormBuilder_14 = new import12.FormBuilder()); }
    return this.__FormBuilder_14;
  }
  createInternal():import1.IqSelect2Module {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._HttpModule_3 = new import5.HttpModule();
    this._ReactiveFormsModule_4 = new import4.ReactiveFormsModule();
    this._IqSelect2Module_5 = new import1.IqSelect2Module();
    return this._IqSelect2Module_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import1.IqSelect2Module)) { return this._IqSelect2Module_5; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import7.RadioControlRegistry)) { return this._RadioControlRegistry_7; }
    if ((token === import8.BrowserXhr)) { return this._BrowserXhr_8; }
    if ((token === import9.ResponseOptions)) { return this._ResponseOptions_9; }
    if ((token === import15.XSRFStrategy)) { return this._XSRFStrategy_10; }
    if ((token === import10.XHRBackend)) { return this._XHRBackend_11; }
    if ((token === import11.RequestOptions)) { return this._RequestOptions_12; }
    if ((token === import16.Http)) { return this._Http_13; }
    if ((token === import12.FormBuilder)) { return this._FormBuilder_14; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const IqSelect2ModuleNgFactory:import0.NgModuleFactory<import1.IqSelect2Module> = new import0.NgModuleFactory(IqSelect2ModuleInjector,import1.IqSelect2Module);